[platformio]
build_dir = bgen

[env:esp32-s3-n16r8]
platform = espressif32
board = esp32-s3-n16r8
framework = espidf
monitor_speed = 115200

[env:esp32-s3-n16r8-minimal]
platform = espressif32
board = esp32-s3-n16r8
framework = espidf
monitor_speed = 115200
build_flags =
    -DCONFIG_FEATURE_UI_TEXT=0
